// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using spacer.Models;

#nullable disable

namespace spacer.Migrations
{
    [DbContext(typeof(SpacerContext))]
    partial class SpacerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("spacer.Models.Comment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("creationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("postId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("postId");

                    b.HasIndex("userId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            id = 1,
                            content = "Great article!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6123),
                            postId = 1,
                            userId = 1
                        },
                        new
                        {
                            id = 2,
                            content = "Very interesting!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6132),
                            postId = 1,
                            userId = 1
                        },
                        new
                        {
                            id = 3,
                            content = "Loved this!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6140),
                            postId = 1,
                            userId = 1
                        },
                        new
                        {
                            id = 4,
                            content = "I agree!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6146),
                            postId = 1,
                            userId = 1
                        },
                        new
                        {
                            id = 5,
                            content = "Great article!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6159),
                            postId = 2,
                            userId = 1
                        },
                        new
                        {
                            id = 6,
                            content = "Very interesting!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6167),
                            postId = 2,
                            userId = 1
                        },
                        new
                        {
                            id = 7,
                            content = "Loved this!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6173),
                            postId = 2,
                            userId = 1
                        },
                        new
                        {
                            id = 8,
                            content = "I agree!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6178),
                            postId = 2,
                            userId = 1
                        },
                        new
                        {
                            id = 9,
                            content = "Great article!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6191),
                            postId = 3,
                            userId = 1
                        },
                        new
                        {
                            id = 10,
                            content = "Very interesting!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6197),
                            postId = 3,
                            userId = 1
                        },
                        new
                        {
                            id = 11,
                            content = "Loved this!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6203),
                            postId = 3,
                            userId = 1
                        },
                        new
                        {
                            id = 12,
                            content = "I agree!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6209),
                            postId = 3,
                            userId = 1
                        },
                        new
                        {
                            id = 13,
                            content = "Great article!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6221),
                            postId = 4,
                            userId = 1
                        },
                        new
                        {
                            id = 14,
                            content = "Very interesting!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6227),
                            postId = 4,
                            userId = 1
                        },
                        new
                        {
                            id = 15,
                            content = "Loved this!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6233),
                            postId = 4,
                            userId = 1
                        },
                        new
                        {
                            id = 16,
                            content = "I agree!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6239),
                            postId = 4,
                            userId = 1
                        },
                        new
                        {
                            id = 17,
                            content = "Nice perspective!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6261),
                            postId = 5,
                            userId = 2
                        },
                        new
                        {
                            id = 18,
                            content = "More details please!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6268),
                            postId = 5,
                            userId = 2
                        },
                        new
                        {
                            id = 19,
                            content = "Can you elaborate?",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6274),
                            postId = 5,
                            userId = 2
                        },
                        new
                        {
                            id = 20,
                            content = "Interesting read!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6305),
                            postId = 5,
                            userId = 2
                        },
                        new
                        {
                            id = 21,
                            content = "Nice perspective!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6318),
                            postId = 6,
                            userId = 2
                        },
                        new
                        {
                            id = 22,
                            content = "More details please!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6324),
                            postId = 6,
                            userId = 2
                        },
                        new
                        {
                            id = 23,
                            content = "Can you elaborate?",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6331),
                            postId = 6,
                            userId = 2
                        },
                        new
                        {
                            id = 24,
                            content = "Interesting read!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6338),
                            postId = 6,
                            userId = 2
                        },
                        new
                        {
                            id = 25,
                            content = "Nice perspective!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6350),
                            postId = 7,
                            userId = 2
                        },
                        new
                        {
                            id = 26,
                            content = "More details please!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6356),
                            postId = 7,
                            userId = 2
                        },
                        new
                        {
                            id = 27,
                            content = "Can you elaborate?",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6362),
                            postId = 7,
                            userId = 2
                        },
                        new
                        {
                            id = 28,
                            content = "Interesting read!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6368),
                            postId = 7,
                            userId = 2
                        },
                        new
                        {
                            id = 29,
                            content = "Nice perspective!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6380),
                            postId = 8,
                            userId = 2
                        },
                        new
                        {
                            id = 30,
                            content = "More details please!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6386),
                            postId = 8,
                            userId = 2
                        },
                        new
                        {
                            id = 31,
                            content = "Can you elaborate?",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6392),
                            postId = 8,
                            userId = 2
                        },
                        new
                        {
                            id = 32,
                            content = "Interesting read!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6398),
                            postId = 8,
                            userId = 2
                        },
                        new
                        {
                            id = 33,
                            content = "Fascinating stuff!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6411),
                            postId = 9,
                            userId = 3
                        },
                        new
                        {
                            id = 34,
                            content = "Totally true!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6418),
                            postId = 9,
                            userId = 3
                        },
                        new
                        {
                            id = 35,
                            content = "Can't wait!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6424),
                            postId = 9,
                            userId = 3
                        },
                        new
                        {
                            id = 36,
                            content = "So true!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6430),
                            postId = 9,
                            userId = 3
                        },
                        new
                        {
                            id = 37,
                            content = "Fascinating stuff!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6442),
                            postId = 10,
                            userId = 3
                        },
                        new
                        {
                            id = 38,
                            content = "Totally true!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6448),
                            postId = 10,
                            userId = 3
                        },
                        new
                        {
                            id = 39,
                            content = "Can't wait!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6454),
                            postId = 10,
                            userId = 3
                        },
                        new
                        {
                            id = 40,
                            content = "So true!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6460),
                            postId = 10,
                            userId = 3
                        },
                        new
                        {
                            id = 41,
                            content = "Fascinating stuff!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6495),
                            postId = 11,
                            userId = 3
                        },
                        new
                        {
                            id = 42,
                            content = "Totally true!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6501),
                            postId = 11,
                            userId = 3
                        },
                        new
                        {
                            id = 43,
                            content = "Can't wait!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6508),
                            postId = 11,
                            userId = 3
                        },
                        new
                        {
                            id = 44,
                            content = "So true!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6514),
                            postId = 11,
                            userId = 3
                        },
                        new
                        {
                            id = 45,
                            content = "Fascinating stuff!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6527),
                            postId = 12,
                            userId = 3
                        },
                        new
                        {
                            id = 46,
                            content = "Totally true!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6533),
                            postId = 12,
                            userId = 3
                        },
                        new
                        {
                            id = 47,
                            content = "Can't wait!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6539),
                            postId = 12,
                            userId = 3
                        },
                        new
                        {
                            id = 48,
                            content = "So true!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6545),
                            postId = 12,
                            userId = 3
                        },
                        new
                        {
                            id = 49,
                            content = "Well said!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6557),
                            postId = 13,
                            userId = 4
                        },
                        new
                        {
                            id = 50,
                            content = "Looking forward!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6562),
                            postId = 13,
                            userId = 4
                        },
                        new
                        {
                            id = 51,
                            content = "Absolutely!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6568),
                            postId = 13,
                            userId = 4
                        },
                        new
                        {
                            id = 52,
                            content = "Keep it up!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6574),
                            postId = 13,
                            userId = 4
                        },
                        new
                        {
                            id = 53,
                            content = "Well said!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6587),
                            postId = 14,
                            userId = 4
                        },
                        new
                        {
                            id = 54,
                            content = "Looking forward!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6593),
                            postId = 14,
                            userId = 4
                        },
                        new
                        {
                            id = 55,
                            content = "Absolutely!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6599),
                            postId = 14,
                            userId = 4
                        },
                        new
                        {
                            id = 56,
                            content = "Keep it up!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6605),
                            postId = 14,
                            userId = 4
                        },
                        new
                        {
                            id = 57,
                            content = "Well said!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6617),
                            postId = 15,
                            userId = 4
                        },
                        new
                        {
                            id = 58,
                            content = "Looking forward!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6623),
                            postId = 15,
                            userId = 4
                        },
                        new
                        {
                            id = 59,
                            content = "Absolutely!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6629),
                            postId = 15,
                            userId = 4
                        },
                        new
                        {
                            id = 60,
                            content = "Keep it up!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6635),
                            postId = 15,
                            userId = 4
                        },
                        new
                        {
                            id = 61,
                            content = "Well said!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6647),
                            postId = 16,
                            userId = 4
                        },
                        new
                        {
                            id = 62,
                            content = "Looking forward!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6653),
                            postId = 16,
                            userId = 4
                        },
                        new
                        {
                            id = 63,
                            content = "Absolutely!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6659),
                            postId = 16,
                            userId = 4
                        },
                        new
                        {
                            id = 64,
                            content = "Keep it up!",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6688),
                            postId = 16,
                            userId = 4
                        });
                });

            modelBuilder.Entity("spacer.Models.Post", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("creationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("forumId")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("forumId");

                    b.HasIndex("userId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            id = 1,
                            content = "Post content",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6073),
                            forumId = 1,
                            title = "Tech Innovations",
                            userId = 1
                        },
                        new
                        {
                            id = 2,
                            content = "Post content",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6153),
                            forumId = 1,
                            title = "Space Discoveries",
                            userId = 1
                        },
                        new
                        {
                            id = 3,
                            content = "Post content",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6184),
                            forumId = 1,
                            title = "Game Releases",
                            userId = 1
                        },
                        new
                        {
                            id = 4,
                            content = "Post content",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6215),
                            forumId = 1,
                            title = "Music Trends",
                            userId = 1
                        },
                        new
                        {
                            id = 5,
                            content = "Post content",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6254),
                            forumId = 2,
                            title = "AI in 2024",
                            userId = 2
                        },
                        new
                        {
                            id = 6,
                            content = "Post content",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6312),
                            forumId = 2,
                            title = "Mars Rover",
                            userId = 2
                        },
                        new
                        {
                            id = 7,
                            content = "Post content",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6344),
                            forumId = 2,
                            title = "New Console",
                            userId = 2
                        },
                        new
                        {
                            id = 8,
                            content = "Post content",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6374),
                            forumId = 2,
                            title = "Top 10 Albums",
                            userId = 2
                        },
                        new
                        {
                            id = 9,
                            content = "Post content",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6404),
                            forumId = 3,
                            title = "Gadgets 2023",
                            userId = 3
                        },
                        new
                        {
                            id = 10,
                            content = "Post content",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6436),
                            forumId = 3,
                            title = "Climate Change",
                            userId = 3
                        },
                        new
                        {
                            id = 11,
                            content = "Post content",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6487),
                            forumId = 3,
                            title = "Indie Games",
                            userId = 3
                        },
                        new
                        {
                            id = 12,
                            content = "Post content",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6520),
                            forumId = 3,
                            title = "Concerts Near Me",
                            userId = 3
                        },
                        new
                        {
                            id = 13,
                            content = "Post content",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6551),
                            forumId = 4,
                            title = "Future of Tech",
                            userId = 4
                        },
                        new
                        {
                            id = 14,
                            content = "Post content",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6581),
                            forumId = 4,
                            title = "Quantum Physics",
                            userId = 4
                        },
                        new
                        {
                            id = 15,
                            content = "Post content",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6611),
                            forumId = 4,
                            title = "VR Experience",
                            userId = 4
                        },
                        new
                        {
                            id = 16,
                            content = "Post content",
                            creationDate = new DateTime(2024, 11, 1, 17, 50, 29, 74, DateTimeKind.Local).AddTicks(6641),
                            forumId = 4,
                            title = "Live Performances",
                            userId = 4
                        });
                });

            modelBuilder.Entity("spacer.Models.Subspace", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Subspaces");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "technology"
                        },
                        new
                        {
                            id = 2,
                            name = "science"
                        },
                        new
                        {
                            id = 3,
                            name = "gaming"
                        },
                        new
                        {
                            id = 4,
                            name = "music"
                        });
                });

            modelBuilder.Entity("spacer.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            id = 1,
                            email = "alice@example.com",
                            name = "alice",
                            password = "password1"
                        },
                        new
                        {
                            id = 2,
                            email = "bob@example.com",
                            name = "bob",
                            password = "password2"
                        },
                        new
                        {
                            id = 3,
                            email = "charlie@example.com",
                            name = "charlie",
                            password = "password3"
                        },
                        new
                        {
                            id = 4,
                            email = "dave@example.com",
                            name = "dave",
                            password = "password4"
                        });
                });

            modelBuilder.Entity("spacer.Models.Comment", b =>
                {
                    b.HasOne("spacer.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("postId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("spacer.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("spacer.Models.Post", b =>
                {
                    b.HasOne("spacer.Models.Subspace", "Subspace")
                        .WithMany("posts")
                        .HasForeignKey("forumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("spacer.Models.User", "User")
                        .WithMany("posts")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subspace");

                    b.Navigation("User");
                });

            modelBuilder.Entity("spacer.Models.Post", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("spacer.Models.Subspace", b =>
                {
                    b.Navigation("posts");
                });

            modelBuilder.Entity("spacer.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("posts");
                });
#pragma warning restore 612, 618
        }
    }
}
